begin;
select plan(116);
select has_table('public','profiles','profiles exists');
select has_function('public','has_permission',array['text'],'permission function exists');
select policies_are('public','profiles',array['profiles_select_self','profiles_update_self'],'profile policies are explicit');
select policies_are('public','audit_logs',array['audit_read'],'audit logs cannot be browser-written');
select col_is_pk('public','profiles','id','profile identity is primary key');
select fk_ok('public','profiles','id','auth','users','id','profile references auth user');
select trigger_is('auth','users','auth_user_created','public','on_auth_user_created','signup creates profile');
select trigger_is('public','user_roles','protect_owner','public','prevent_owner_change','owner cannot be demoted');
select has_table('public','account_deletion_requests','deletion request table exists');
select policies_are('public','account_deletion_requests',array['deletion_requests_own_create','deletion_requests_own_read'],'deletion requests are user scoped');
select has_function('public','accept_staff_invitation',array['text'],'invitation acceptance is database controlled');
select has_function('public','transfer_ownership',array['uuid','text'],'ownership transfer is explicit');
select has_table('public','foods','food catalog exists');
select has_table('public','food_versions','food versions exist');
select has_table('public','food_version_nutrients','flexible food nutrients exist');
select has_table('public','provider_food_cache','provider cache exists');
select ok(has_table_privilege('service_role','public.provider_food_cache','SELECT,INSERT,UPDATE,DELETE'),'service role can maintain external food cache');
select policies_are('public','foods',array['foods_owner_create','foods_owner_update','foods_read'],'foods are catalog or owner scoped');
select policies_are('public','food_version_nutrients',array['food_nutrients_read'],'nutrients inherit food visibility');
select has_function('public','search_food_catalog',array['text','integer','integer'],'catalog search is database backed');
select col_is_fk('public','foods','current_version_id','foods point to a version');
select has_table('public','nutrition_profiles','nutrition profiles exist');
select has_table('public','user_nutrient_targets','personal targets exist');
select has_table('public','diary_days','diary days exist');
select has_table('public','meal_entries','meal entries exist');
select has_table('public','meal_entry_nutrient_snapshots','immutable snapshots exist');
select policies_are('public','diary_days',array['diary_days_own'],'diary days are user scoped');
select policies_are('public','meal_entries',array['entries_own'],'entries inherit diary ownership');
select policies_are('public','meal_entry_nutrient_snapshots',array['snapshots_own_read'],'snapshots are browser read-only');
select has_function('public','log_food_entry',array['uuid','numeric','text','date','time without time zone','text'],'logging is atomic');
select has_function('public','log_photo_meal',array['jsonb','text','date','time without time zone'],'reviewed photo meals are logged atomically');
select has_function('public','daily_nutrient_totals',array['date'],'aggregation is centralized');
select has_function('public','update_food_entry',array['uuid','numeric','text','text'],'entry updates resnapshot atomically');
select has_function('public','duplicate_food_entry',array['uuid'],'entry duplication preserves snapshots');
select has_table('public','nutrient_projections','projection records exist');
select has_table('public','nutrient_projection_references','projection provenance exists');
select has_table('public','projection_reviews','projection reviews exist');
select has_table('public','projection_recalculations','projection recalculations exist');
select has_table('public','projection_settings','projection thresholds exist');
select policies_are('public','nutrient_projections',array['projections_manage','projections_read'],'projection access is scoped');
select policies_are('public','projection_settings',array['projection_settings_manage','projection_settings_read'],'threshold access is protected');
select has_function('public','projection_category',array['numeric'],'confidence categories are centralized');
select has_function('public','review_projection',array['uuid','text','text'],'reviews are audited operations');
select has_function('public','request_projection_recalculation',array['uuid','text'],'recalculation requests are explicit');
select trigger_is('public','nutrient_projections','projection_confidence_before_write','public','enforce_projection_confidence','confidence categories follow scores');
select has_table('public','subscriptions','subscriptions exist');
select has_table('public','stripe_events','idempotent Stripe events exist');
select has_table('public','promo_codes','hashed promo codes exist');
select has_table('public','promo_code_redemptions','redemptions exist');
select has_table('public','access_grants','complimentary grants exist');
select policies_are('public','subscriptions',array['subscriptions_own_read'],'subscriptions are browser read-only');
select policies_are('public','stripe_events',array['stripe_events_admin_read'],'Stripe events are browser read-only');
select policies_are('public','promo_codes',array['promo_codes_admin_all'],'promo code management is permission protected');
select has_function('public','normalize_promo_code',array['text'],'promo normalization is centralized');
select has_function('public','redeem_promo_code',array['text'],'promo redemption is atomic');
select has_function('public','has_premium_access',array['uuid'],'access checks are server-side');
select has_table('public','recipes','recipes exist');
select has_table('public','recipe_versions','recipe versions exist');
select has_table('public','recipe_ingredient_nutrient_snapshots','ingredient lineage exists');
select has_table('public','recipe_nutrient_snapshots','recipe totals exist');
select has_table('public','saved_meals','saved meals exist');
select has_table('public','saved_meal_items','saved meal items exist');
select has_table('public','weight_logs','weight logs exist');
select has_table('public','favorite_foods','favorites exist');
select policies_are('public','recipes',array['recipes_own'],'recipes are user scoped');
select policies_are('public','weight_logs',array['weights_own'],'weights are user scoped');
select policies_are('public','recipe_ingredient_nutrient_snapshots',array['recipe_ingredient_snapshots_read'],'recipe snapshots are browser read-only');
select has_function('public','create_recipe',array['text','text','numeric','jsonb'],'recipe creation is atomic');
select has_function('public','recalculate_recipe',array['uuid'],'recipe aggregation is centralized');
select has_function('public','save_diary_meal',array['uuid','text'],'diary meals can be saved');
select has_function('public','log_saved_meal',array['uuid','date','text'],'saved meals preserve food versions');
select has_table('public','admin_user_notes','admin notes exist');
select has_table('public','admin_access_logs','private access logs exist');
select has_table('public','food_reports','food moderation reports exist');
select has_table('public','custom_food_submissions','custom food review exists');
select has_table('public','provider_nutrient_mappings','provider mappings exist');
select has_table('public','product_events','product events exist');
select has_table('public','daily_analytics_rollups','analytics rollups exist');
select has_table('public','content_blocks','content blocks exist');
select has_table('public','feature_flags','feature flags exist');
select has_table('public','automation_definitions','automation definitions exist');
select has_table('public','automation_runs','automation runs exist');
select has_table('public','system_incidents','system incidents exist');
select policies_are('public','admin_user_notes',array['admin_notes_manage'],'admin notes require user permission');
select policies_are('public','admin_access_logs',array['admin_access_read'],'private access logs are read protected');
select policies_are('public','provider_nutrient_mappings',array['mappings_manage','mappings_read'],'nutrient mappings have granular management');
select policies_are('public','feature_flags',array['flags_manage','flags_read'],'feature flags are managed separately');
select policies_are('public','automation_definitions',array['automations_manage'],'automations require permission');
select policies_are('public','product_events',array['events_own_insert'],'events cannot be browser-read');
select has_function('public','admin_search_users',array['text','integer'],'user search is permission protected');
select has_function('public','admin_set_user_suspension',array['uuid','boolean','text'],'suspension is audited');
select has_function('public','log_private_nutrition_access',array['uuid','text'],'private data access requires reason');
select has_function('public','process_projection_recalculation',array['uuid'],'projection recalculation is executable');
select has_function('public','run_automation',array['uuid','jsonb'],'automation tests are controlled');
select has_table('public','rate_limit_buckets','shared rate limits exist');
select has_table('public','app_settings','production settings exist');
select has_table('public','operational_events','operational events exist');
select policies_are('public','rate_limit_buckets',array[]::text[],'rate buckets have no browser policies');
select policies_are('public','app_settings',array['app_settings_admin_read','app_settings_manage'],'settings are permission protected');
select policies_are('public','operational_events',array['operational_events_read'],'operational events are browser read-only');
select has_function('public','consume_rate_limit',array['text','text','integer','integer'],'rate limiting is shared and atomic');
select has_function('public','purge_expired_operational_data',array[]::text[],'retention cleanup is explicit');
select is((select count(*) from public.nutrients where is_core),76::bigint,'complete core and advanced nutrient catalog is installed');
select is((select count(*) from public.nutrients n join public.nutrient_categories c on c.id=n.category_id where c.key='vitamins'),14::bigint,'vitamin catalog is complete');
select is((select count(*) from public.nutrients n join public.nutrient_categories c on c.id=n.category_id where c.key='minerals'),10::bigint,'mineral catalog is complete');
select has_function('public','apply_entry_nutrient_overrides',array['uuid','jsonb'],'diary nutrient corrections are centralized');
select has_function('public','import_normalized_food',array['jsonb'],'provider imports are security controlled');
select has_function('public','recommend_foods_for_nutrients',array['text[]','integer'],'food recommendations are centralized');
select has_function('public','recommend_foods_for_gaps',array['jsonb','integer'],'daily nutrient gap recommendations are weighted');
select is((select count(*) from public.food_sources where key='nih_dsld'),1::bigint,'NIH supplement source is registered');
select is((select count(*) from public.food_sources where key='health_canada_cnf'),1::bigint,'Health Canada source is registered');
select is((select count(*) from public.search_food_catalog('eggs',20,0) where name='Egg, whole, cooked'),1::bigint,'eggs finds the quick generic egg');
select cmp_ok((select count(*) from public.search_food_catalog('potatoes',20,0) where name like 'Potato%'),'>=',4::bigint,'potatoes finds generic and specific potato choices');
select is((select count(*) from public.search_food_catalog('protein powder',20,0) where name like 'Protein powder%'),2::bigint,'protein supplement choices are searchable');
select cmp_ok((select count(*) from public.search_food_catalog('fish oil',20,0) where name like 'Fish oil%'),'>=',2::bigint,'fish oil supplement choices are searchable');
select is((select count(*) from public.search_food_catalog('mac and cheese',20,0)),4::bigint,'mac and cheese finds branded and generic demo foods');
select * from finish();
rollback;
