import type { NormalizedNutrient } from "./types";
export const nutrientAliases: Record<string, string> = {
  "1008": "energy_kcal",
  "2047": "energy_kcal",
  "1003": "protein",
  "1005": "carbohydrate",
  "1004": "fat",
  "1079": "fiber",
  "1093": "sodium",
  "1106": "vitamin_a",
  "1162": "vitamin_c",
  "1114": "vitamin_d",
  "1109": "vitamin_e",
  "1185": "vitamin_k",
  "1165": "thiamin",
  "1166": "riboflavin",
  "1167": "niacin",
  "1170": "pantothenic_acid",
  "1175": "vitamin_b6",
  "1177": "folate",
  "1178": "vitamin_b12",
  "1180": "choline",
  "1087": "calcium",
  "1089": "iron",
  "1092": "potassium",
  "1090": "magnesium",
  "1095": "zinc",
  "1091": "phosphorus",
  "1103": "selenium",
  "1098": "copper",
  "1101": "manganese",
  "2000": "total_sugars",
  "1235": "added_sugars",
  "1011": "glucose",
  "1012": "fructose",
  "1010": "sucrose",
  "1013": "lactose",
  "1258": "saturated_fat",
  "1292": "monounsaturated_fat",
  "1293": "polyunsaturated_fat",
  "1257": "trans_fat",
  "1253": "cholesterol",
  "1215": "leucine",
  "1216": "lysine",
  "1217": "methionine",
  "1212": "tryptophan",
  "1213": "threonine",
  "1214": "isoleucine",
  "1219": "phenylalanine",
  "1220": "tyrosine",
  "1221": "valine",
  "1099": "fluoride",
  "1107": "beta_carotene",
  "1108": "alpha_carotene",
  "1122": "lycopene",
  "1123": "lutein_zeaxanthin",
  "1057": "caffeine",
  "1018": "alcohol",
  "1051": "water",
  "energy-kcal": "energy_kcal",
  proteins: "protein",
  carbohydrates: "carbohydrate",
  fat: "fat",
  fiber: "fiber",
  sodium: "sodium",
  "vitamin-a": "vitamin_a",
  "vitamin-c": "vitamin_c",
  "vitamin-d": "vitamin_d",
  "vitamin-e": "vitamin_e",
  "vitamin-k": "vitamin_k",
  "vitamin-b1": "thiamin",
  "vitamin-b2": "riboflavin",
  "vitamin-pp": "niacin",
  "vitamin-b6": "vitamin_b6",
  "vitamin-b9": "folate",
  "vitamin-b12": "vitamin_b12",
  calcium: "calcium",
  iron: "iron",
  potassium: "potassium",
  magnesium: "magnesium",
  zinc: "zinc",
  phosphorus: "phosphorus",
  selenium: "selenium",
  copper: "copper",
  manganese: "manganese",
  "omega-3-fat": "omega_3",
};
export const nutrientNameAliases: Record<string, string> = {
  "energy (kcal)": "energy_kcal",
  protein: "protein",
  carbohydrate: "carbohydrate",
  "total fat": "fat",
  "fat (total lipids)": "fat",
  "fibre, total dietary": "fiber",
  "fiber, total dietary": "fiber",
  "dietary fiber": "fiber",
  "total dietary fiber": "fiber",
  calories: "energy_kcal",
  "total carbohydrates": "carbohydrate",
  "total carbohydrate": "carbohydrate",
  sugar: "total_sugars",
  "total sugars": "total_sugars",
  "sodium, na": "sodium",
  sodium: "sodium",
  "vitamin a": "vitamin_a",
  "vitamin c": "vitamin_c",
  "vitamin d": "vitamin_d",
  "vitamin e": "vitamin_e",
  "vitamin k": "vitamin_k",
  thiamin: "thiamin",
  thiamine: "thiamin",
  riboflavin: "riboflavin",
  niacin: "niacin",
  "pantothenic acid": "pantothenic_acid",
  "vitamin b6": "vitamin_b6",
  biotin: "biotin",
  folate: "folate",
  "folic acid": "folate",
  "vitamin b12": "vitamin_b12",
  choline: "choline",
  "calcium, ca": "calcium",
  calcium: "calcium",
  "iron, fe": "iron",
  iron: "iron",
  "potassium, k": "potassium",
  potassium: "potassium",
  "magnesium, mg": "magnesium",
  magnesium: "magnesium",
  "zinc, zn": "zinc",
  zinc: "zinc",
  "phosphorus, p": "phosphorus",
  phosphorus: "phosphorus",
  "selenium, se": "selenium",
  selenium: "selenium",
  "copper, cu": "copper",
  copper: "copper",
  "manganese, mn": "manganese",
  manganese: "manganese",
  "omega-3 fatty acids": "omega_3",
  "omega 3 fatty acids": "omega_3",
  "18:2 n-6 c,c": "omega_6",
  "18:2 n-6": "omega_6",
  "18:3 n-3 c,c,c (ala)": "ala",
  "18:3 n-3 (ala)": "ala",
  "20:5 n-3 (epa)": "epa",
  "22:6 n-3 (dha)": "dha",
  "sugars, total": "total_sugars",
  "sugars, total including nlea": "total_sugars",
  "added sugars": "added_sugars",
  glucose: "glucose",
  fructose: "fructose",
  sucrose: "sucrose",
  lactose: "lactose",
  "fatty acids, total saturated": "saturated_fat",
  "fatty acids, total monounsaturated": "monounsaturated_fat",
  "fatty acids, total polyunsaturated": "polyunsaturated_fat",
  "fatty acids, total trans": "trans_fat",
  cholesterol: "cholesterol",
  leucine: "leucine",
  lysine: "lysine",
  methionine: "methionine",
  tryptophan: "tryptophan",
  threonine: "threonine",
  isoleucine: "isoleucine",
  phenylalanine: "phenylalanine",
  tyrosine: "tyrosine",
  valine: "valine",
  iodine: "iodine",
  chromium: "chromium",
  molybdenum: "molybdenum",
  fluoride: "fluoride",
  chloride: "chloride",
  boron: "boron",
  "beta-carotene": "beta_carotene",
  "carotene, beta": "beta_carotene",
  "alpha-carotene": "alpha_carotene",
  "carotene, alpha": "alpha_carotene",
  lycopene: "lycopene",
  "lutein + zeaxanthin": "lutein_zeaxanthin",
  "lutein and zeaxanthin": "lutein_zeaxanthin",
  phytosterols: "phytosterols",
  caffeine: "caffeine",
  alcohol: "alcohol",
  water: "water",
};
export const trackedNutrientKeys = [
  "energy_kcal",
  "protein",
  "carbohydrate",
  "fat",
  "fiber",
  "sodium",
  "vitamin_a",
  "vitamin_c",
  "vitamin_d",
  "vitamin_e",
  "vitamin_k",
  "thiamin",
  "riboflavin",
  "niacin",
  "pantothenic_acid",
  "vitamin_b6",
  "biotin",
  "folate",
  "vitamin_b12",
  "choline",
  "calcium",
  "potassium",
  "magnesium",
  "zinc",
  "phosphorus",
  "selenium",
  "copper",
  "manganese",
  "iron",
  "omega_3",
  "total_sugars",
  "added_sugars",
  "glucose",
  "fructose",
  "sucrose",
  "lactose",
  "saturated_fat",
  "monounsaturated_fat",
  "polyunsaturated_fat",
  "trans_fat",
  "cholesterol",
  "omega_6",
  "ala",
  "epa",
  "dha",
  "leucine",
  "lysine",
  "methionine",
  "tryptophan",
  "threonine",
  "isoleucine",
  "phenylalanine",
  "tyrosine",
  "valine",
  "iodine",
  "chromium",
  "molybdenum",
  "fluoride",
  "chloride",
  "boron",
  "beta_carotene",
  "alpha_carotene",
  "lycopene",
  "lutein_zeaxanthin",
  "phytosterols",
  "caffeine",
  "alcohol",
  "water",
  "total_polyphenols",
  "flavonols",
  "flavan_3_ols",
  "flavanones",
  "anthocyanidins",
  "isoflavones",
  "proanthocyanidins",
  "flavones",
] as const;
export function completeness(nutrients: NormalizedNutrient[]) {
  const present = new Set(
    nutrients.filter((n) => n.amountPer100g !== null).map((n) => n.key),
  );
  return Math.round(
    (trackedNutrientKeys.filter((key) => present.has(key)).length /
      trackedNutrientKeys.length) *
      100,
  );
}
export function safeNumber(value: unknown): number | null {
  const number = typeof value === "number" ? value : Number(value);
  return Number.isFinite(number) && number >= 0 ? number : null;
}
