begin;
create temp table cnf_food(food_code integer,food_description_en text,food_description_fr text,alternate_description_en text,alternate_description_fr text,food_source_code text,usda_ndb_code text,cnf_food_group_code text,comment_en text,comment_fr text,scientific_name text,food_last_updated_date text);
create temp table cnf_amount(food_code integer,nutrient_code integer,nutrient_amount numeric,std_error text,observations text,nutrient_source_code text,nutrient_last_updated_date text);
\copy cnf_food from '/tmp/cnf_2026/Food_Name.csv' with(format csv,header true,encoding 'UTF8');
\copy cnf_amount from '/tmp/cnf_2026/Nutrient_Amount.csv' with(format csv,header true,encoding 'UTF8');

create temp table cnf_map(nutrient_code integer primary key,nutrient_key text not null,conversion numeric not null default 1);
insert into cnf_map values
(203,'protein',1),(204,'fat',1),(205,'carbohydrate',1),(208,'energy_kcal',1),(210,'sucrose',1),(211,'glucose',1),(212,'fructose',1),(213,'lactose',1),(221,'alcohol',1),(255,'water',1),(262,'caffeine',1),(269,'total_sugars',1),(291,'fiber',1),(301,'calcium',1),(303,'iron',1),(304,'magnesium',1),(305,'phosphorus',1),(306,'potassium',1),(307,'sodium',1),(309,'zinc',1),(312,'copper',1),(315,'manganese',1),(317,'selenium',1),(320,'vitamin_a',1),(321,'beta_carotene',1),(322,'alpha_carotene',1),(323,'vitamin_e',1),(328,'vitamin_d',1),(337,'lycopene',1),(338,'lutein_zeaxanthin',1),(401,'vitamin_c',1),(404,'thiamin',1),(405,'riboflavin',1),(406,'niacin',1),(410,'pantothenic_acid',1),(415,'vitamin_b6',1),(416,'biotin',1),(417,'folate',1),(418,'vitamin_b12',1),(421,'choline',1),(430,'vitamin_k',1),(501,'tryptophan',1),(502,'threonine',1),(503,'isoleucine',1),(504,'leucine',1),(505,'lysine',1),(506,'methionine',1),(508,'phenylalanine',1),(509,'tyrosine',1),(510,'valine',1),(601,'cholesterol',1),(605,'trans_fat',1),(606,'saturated_fat',1),(621,'dha',1000),(629,'epa',1000),(636,'phytosterols',1),(645,'monounsaturated_fat',1),(646,'polyunsaturated_fat',1),(675,'omega_6',1000),(851,'ala',1000);

create temp table cnf_entity as
select f.food_code,coalesce(existing.food_id,(substr(md5('cnf-food:'||f.food_code),1,8)||'-'||substr(md5('cnf-food:'||f.food_code),9,4)||'-4'||substr(md5('cnf-food:'||f.food_code),14,3)||'-a'||substr(md5('cnf-food:'||f.food_code),18,3)||'-'||substr(md5('cnf-food:'||f.food_code),21,12))::uuid)food_id,coalesce(existing.version_id,(substr(md5('cnf-version:'||f.food_code),1,8)||'-'||substr(md5('cnf-version:'||f.food_code),9,4)||'-4'||substr(md5('cnf-version:'||f.food_code),14,3)||'-a'||substr(md5('cnf-version:'||f.food_code),18,3)||'-'||substr(md5('cnf-version:'||f.food_code),21,12))::uuid)version_id
from cnf_food f cross join(select id from public.food_sources where key='health_canada_cnf')s left join lateral(select fv.food_id,fv.id version_id from public.food_versions fv where fv.source_id=s.id and fv.provider_record_id=f.food_code::text limit 1)existing on true;

insert into public.foods(id,name,brand,description,food_type,owner_id,is_public,is_verified) select e.food_id,left(f.food_description_en,200),null,'Health Canada Canadian Nutrient File 2026','generic',null,true,true from cnf_food f join cnf_entity e using(food_code) on conflict(id)do update set name=excluded.name,description=excluded.description,is_public=true,is_verified=true,deleted_at=null;

with source as(select id from public.food_sources where key='health_canada_cnf')insert into public.food_versions(id,food_id,version,source_id,provider_record_id,data_completeness,contains_projections,source_payload) select e.version_id,e.food_id,1,s.id,f.food_code::text,0,false,jsonb_build_object('provider','health_canada_cnf','providerId',f.food_code::text,'name',f.food_description_en,'release','2026') from cnf_food f join cnf_entity e using(food_code)cross join source s on conflict(id)do update set source_payload=excluded.source_payload,provider_record_id=excluded.provider_record_id;

update public.foods f set current_version_id=e.version_id from cnf_entity e where f.id=e.food_id;

insert into public.food_servings(id,food_version_id,label,amount,unit,gram_weight,is_default)select (substr(md5('cnf-serving:'||e.food_code),1,8)||'-'||substr(md5('cnf-serving:'||e.food_code),9,4)||'-4'||substr(md5('cnf-serving:'||e.food_code),14,3)||'-a'||substr(md5('cnf-serving:'||e.food_code),18,3)||'-'||substr(md5('cnf-serving:'||e.food_code),21,12))::uuid,e.version_id,'100 g',1,'serving',100,true from cnf_entity e where not exists(select 1 from public.food_servings fs where fs.food_version_id=e.version_id and fs.is_default)on conflict(id)do update set gram_weight=100,is_default=true;

with rows as(select e.version_id,n.id nutrient_id,a.nutrient_amount*m.conversion amount,n.default_unit_id,m.nutrient_code from cnf_amount a join cnf_entity e using(food_code)join cnf_map m using(nutrient_code)join public.nutrients n on n.key=m.nutrient_key where a.nutrient_amount>=0)
insert into public.food_version_nutrients(food_version_id,nutrient_id,amount_per_100g,unit_id,classification,source_value,source_basis)select version_id,nutrient_id,amount,default_unit_id,case when amount=0 then'confirmed_zero'else'provider_reported'end,amount,'Health Canada CNF 2026 nutrient code '||nutrient_code from rows on conflict(food_version_id,nutrient_id)do update set amount_per_100g=excluded.amount_per_100g,classification=excluded.classification,source_value=excluded.source_value,source_basis=excluded.source_basis;

update public.food_versions fv set data_completeness=q.coverage from(select fvn.food_version_id,round(count(*)*100.0/76)::integer coverage from public.food_version_nutrients fvn where fvn.food_version_id in(select version_id from cnf_entity)group by fvn.food_version_id)q where fv.id=q.food_version_id;
commit;
