begin;
insert into public.permissions(key,description) values
('food.manage','Moderate foods and reports'),('nutrients.manage','Manage nutrient provider mappings'),('analytics.read','Read aggregate analytics'),('content.manage','Manage public content'),('feature_flags.manage','Manage feature flags'),('automations.manage','Manage and run automations'),('system_health.read','Read system health'),('audit.manage','Read administrative audit records') on conflict do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r cross join public.permissions p where r.key='owner' and p.key in('food.manage','nutrients.manage','analytics.read','content.manage','feature_flags.manage','automations.manage','system_health.read','audit.manage') on conflict do nothing;

create table public.admin_user_notes(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,author_id uuid not null references auth.users,note text not null check(length(trim(note))>=3),created_at timestamptz not null default now());
create table public.admin_access_logs(id uuid primary key default gen_random_uuid(),actor_id uuid not null references auth.users,target_user_id uuid not null references auth.users,access_type text not null,reason text not null check(length(trim(reason))>=10),created_at timestamptz not null default now());
create table public.food_reports(id uuid primary key default gen_random_uuid(),food_id uuid not null references public.foods,reporter_id uuid not null references auth.users,reason text not null,details text,status text not null default 'open' check(status in('open','reviewing','resolved','rejected')),reviewed_by uuid references auth.users,reviewed_at timestamptz,resolution_notes text,created_at timestamptz not null default now());
create table public.custom_food_submissions(id uuid primary key default gen_random_uuid(),food_id uuid not null references public.foods,submitted_by uuid not null references auth.users,status text not null default 'pending' check(status in('pending','approved','rejected')),reviewed_by uuid references auth.users,reviewed_at timestamptz,reason text,created_at timestamptz not null default now());
create table public.provider_nutrient_mappings(id uuid primary key default gen_random_uuid(),provider_key text not null,provider_nutrient_code text not null,nutrient_id uuid not null references public.nutrients,source_unit text,conversion_factor numeric(18,8) not null default 1,is_active boolean not null default true,created_by uuid references auth.users,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(provider_key,provider_nutrient_code));
create trigger provider_mappings_updated before update on public.provider_nutrient_mappings for each row execute function public.set_updated_at();
create table public.product_events(id bigint generated always as identity primary key,user_id uuid references auth.users on delete set null,event_name text not null,properties jsonb not null default '{}',occurred_at timestamptz not null default now());
create index product_events_name_time on public.product_events(event_name,occurred_at desc);
create table public.daily_analytics_rollups(rollup_date date primary key,total_users bigint not null default 0,active_users bigint not null default 0,paid_users bigint not null default 0,complimentary_users bigint not null default 0,foods_logged bigint not null default 0,food_searches bigint not null default 0,no_result_searches bigint not null default 0,projections_used bigint not null default 0,generated_at timestamptz not null default now());
create table public.content_blocks(id uuid primary key default gen_random_uuid(),key text not null unique,title text not null,body text not null,is_published boolean not null default false,updated_by uuid references auth.users,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create trigger content_blocks_updated before update on public.content_blocks for each row execute function public.set_updated_at();
create table public.feature_flags(id uuid primary key default gen_random_uuid(),key text not null unique,description text not null,is_enabled boolean not null default false,configuration jsonb not null default '{}',updated_by uuid references auth.users,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create trigger feature_flags_updated before update on public.feature_flags for each row execute function public.set_updated_at();
create table public.automation_definitions(id uuid primary key default gen_random_uuid(),key text not null unique,name text not null,trigger_type text not null,conditions jsonb not null default '{}',action_type text not null,is_active boolean not null default false,last_run_at timestamptz,last_success_at timestamptz,last_failure_at timestamptz,execution_count bigint not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create trigger automation_definitions_updated before update on public.automation_definitions for each row execute function public.set_updated_at();
create table public.automation_runs(id uuid primary key default gen_random_uuid(),automation_id uuid not null references public.automation_definitions,trigger_payload jsonb not null default '{}',status text not null check(status in('queued','running','succeeded','failed','skipped')),started_at timestamptz,finished_at timestamptz,error text,created_at timestamptz not null default now());
create table public.system_incidents(id uuid primary key default gen_random_uuid(),incident_type text not null,severity text not null check(severity in('info','warning','error','critical')),status text not null default 'open' check(status in('open','investigating','resolved')),summary text not null,details jsonb not null default '{}',resolved_at timestamptz,created_at timestamptz not null default now());

insert into public.feature_flags(key,description) values('experimental_projections','Allow specifically enabled experimental projection research features'),('camera_barcode_scanning','Enable camera-based barcode scanning'),('recurring_meals','Enable recurring meal scheduling');
insert into public.content_blocks(key,title,body) values('nutrition_disclaimer','Nutrition disclaimer','This application is for education and tracking only and does not diagnose, treat, cure, or prevent medical conditions.');
insert into public.automation_definitions(key,name,trigger_type,action_type) values
('welcome_email','Welcome email','user.created','email'),('verification_reminder','Verification reminder','user.unverified','email'),('onboarding_reminder','Onboarding reminder','onboarding.incomplete','email'),('payment_failed','Payment failed','stripe.payment_failed','email'),('weekly_report','Weekly nutrition report','schedule.weekly','report'),('projection_review','Projection review required','projection.pending','admin_notification'),('provider_failure','Provider failure','provider.failed','incident'),('stripe_webhook_failure','Stripe webhook failure','stripe.webhook_failed','incident');

create or replace function public.admin_search_users(search_text text default '',result_limit integer default 50) returns table(user_id uuid,email text,created_at timestamptz,last_sign_in_at timestamptz,suspended_at timestamptz,onboarding_completed_at timestamptz,has_premium boolean) language plpgsql stable security definer set search_path='' as $$begin if not public.has_permission('users.manage') then raise exception 'Permission denied';end if;return query select u.id,u.email::text,u.created_at,u.last_sign_in_at,p.suspended_at,p.onboarding_completed_at,public.has_premium_access(u.id) from auth.users u join public.profiles p on p.id=u.id where trim(search_text)='' or u.email ilike '%'||trim(search_text)||'%' order by u.created_at desc limit least(greatest(result_limit,1),100);end$$;
revoke all on function public.admin_search_users(text,integer) from public,anon;grant execute on function public.admin_search_users(text,integer) to authenticated;
create or replace function public.admin_set_user_suspension(target_user uuid,suspend boolean,action_reason text) returns void language plpgsql security definer set search_path='' as $$begin if not public.has_permission('users.manage') then raise exception 'Permission denied';end if;if length(trim(action_reason))<10 then raise exception 'Meaningful reason required';end if;if exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.user_id=target_user and r.key='owner') then raise exception 'Owner cannot be suspended';end if;update public.profiles set suspended_at=case when suspend then now() else null end where id=target_user;insert into public.audit_logs(actor_id,action,target_type,target_id,reason) values(auth.uid(),case when suspend then 'user.suspend' else 'user.reactivate' end,'user',target_user::text,trim(action_reason));end$$;
revoke all on function public.admin_set_user_suspension(uuid,boolean,text) from public,anon;grant execute on function public.admin_set_user_suspension(uuid,boolean,text) to authenticated;
create or replace function public.log_private_nutrition_access(target_user uuid,access_reason text) returns uuid language plpgsql security definer set search_path='' as $$declare log_id uuid;begin if not public.has_permission('nutrition.private.read') then raise exception 'Permission denied';end if;if length(trim(access_reason))<10 then raise exception 'Meaningful reason required';end if;insert into public.admin_access_logs(actor_id,target_user_id,access_type,reason) values(auth.uid(),target_user,'private_nutrition',trim(access_reason)) returning id into log_id;insert into public.audit_logs(actor_id,action,target_type,target_id,reason) values(auth.uid(),'nutrition.private_access','user',target_user::text,trim(access_reason));return log_id;end$$;
revoke all on function public.log_private_nutrition_access(uuid,text) from public,anon;grant execute on function public.log_private_nutrition_access(uuid,text) to authenticated;
create or replace function public.process_projection_recalculation(p_request_id uuid) returns void language plpgsql security definer set search_path='' as $$declare request public.projection_recalculations%rowtype;new_value numeric;low_value numeric;high_value numeric;begin if not public.has_permission('projections.manage') then raise exception 'Permission denied';end if;select * into request from public.projection_recalculations where id=p_request_id and status='queued' for update;if request.id is null then raise exception 'Queued request not found';end if;update public.projection_recalculations set status='running' where id=request.id;select percentile_cont(.5) within group(order by reference_value),min(reference_value),max(reference_value) into new_value,low_value,high_value from public.nutrient_projection_references where projection_id=request.projection_id and reference_value is not null;if new_value is null then update public.projection_recalculations set status='failed',completed_at=now(),error='No numeric references' where id=request.id;return;end if;update public.nutrient_projections set value=new_value,lower_bound=low_value,upper_bound=high_value,status='pending',reviewed_by=null,reviewed_at=null,explanation=explanation||' Recalculated from current reference median.' where id=request.projection_id;update public.projection_recalculations set status='completed',completed_at=now() where id=request.id;insert into public.audit_logs(actor_id,action,target_type,target_id,reason) values(auth.uid(),'projection.recalculation_complete','nutrient_projection',request.projection_id::text,request.reason);end$$;
revoke all on function public.process_projection_recalculation(uuid) from public,anon;grant execute on function public.process_projection_recalculation(uuid) to authenticated;

create or replace function public.run_automation(p_automation_id uuid,p_payload jsonb default '{}') returns uuid language plpgsql security definer set search_path='' as $$declare automation public.automation_definitions%rowtype;run_id uuid;begin if not public.has_permission('automations.manage') then raise exception 'Permission denied';end if;select * into automation from public.automation_definitions where id=p_automation_id;if automation.id is null then raise exception 'Automation not found';end if;insert into public.automation_runs(automation_id,trigger_payload,status,started_at) values(automation.id,p_payload,case when automation.is_active then 'succeeded' else 'skipped' end,now()) returning id into run_id;update public.automation_runs set finished_at=now() where id=run_id;update public.automation_definitions set last_run_at=now(),last_success_at=case when is_active then now() else last_success_at end,execution_count=execution_count+1 where id=automation.id;insert into public.audit_logs(actor_id,action,target_type,target_id,reason) values(auth.uid(),'automation.test','automation',automation.id::text,'Authorized manual automation test');return run_id;end$$;
revoke all on function public.run_automation(uuid,jsonb) from public,anon;grant execute on function public.run_automation(uuid,jsonb) to authenticated;

alter table public.admin_user_notes enable row level security;alter table public.admin_access_logs enable row level security;alter table public.food_reports enable row level security;alter table public.custom_food_submissions enable row level security;alter table public.provider_nutrient_mappings enable row level security;alter table public.product_events enable row level security;alter table public.daily_analytics_rollups enable row level security;alter table public.content_blocks enable row level security;alter table public.feature_flags enable row level security;alter table public.automation_definitions enable row level security;alter table public.automation_runs enable row level security;alter table public.system_incidents enable row level security;
create policy admin_notes_manage on public.admin_user_notes for all using(public.has_permission('users.manage')) with check(public.has_permission('users.manage'));create policy admin_access_read on public.admin_access_logs for select using(public.has_permission('audit.manage'));create policy food_reports_own_create on public.food_reports for insert with check(reporter_id=auth.uid());create policy food_reports_manage on public.food_reports for all using(public.has_permission('food.manage')) with check(public.has_permission('food.manage'));create policy submissions_own_read on public.custom_food_submissions for select using(submitted_by=auth.uid() or public.has_permission('food.manage'));create policy submissions_manage on public.custom_food_submissions for all using(public.has_permission('food.manage')) with check(public.has_permission('food.manage'));create policy mappings_read on public.provider_nutrient_mappings for select to authenticated using(true);create policy mappings_manage on public.provider_nutrient_mappings for all using(public.has_permission('nutrients.manage')) with check(public.has_permission('nutrients.manage'));create policy events_own_insert on public.product_events for insert with check(user_id=auth.uid() or user_id is null);create policy analytics_read on public.daily_analytics_rollups for select using(public.has_permission('analytics.read'));create policy content_public_read on public.content_blocks for select using(is_published or public.has_permission('content.manage'));create policy content_manage on public.content_blocks for all using(public.has_permission('content.manage')) with check(public.has_permission('content.manage'));create policy flags_read on public.feature_flags for select to authenticated using(true);create policy flags_manage on public.feature_flags for all using(public.has_permission('feature_flags.manage')) with check(public.has_permission('feature_flags.manage'));create policy automations_manage on public.automation_definitions for all using(public.has_permission('automations.manage')) with check(public.has_permission('automations.manage'));create policy automation_runs_manage on public.automation_runs for all using(public.has_permission('automations.manage')) with check(public.has_permission('automations.manage'));create policy incidents_read on public.system_incidents for select using(public.has_permission('system_health.read'));create policy incidents_manage on public.system_incidents for all using(public.has_permission('system_health.read')) with check(public.has_permission('system_health.read'));
commit;
