begin;
create table public.favorite_foods(user_id uuid not null references auth.users on delete cascade,food_id uuid not null references public.foods on delete cascade,created_at timestamptz not null default now(),primary key(user_id,food_id));
create table public.weight_logs(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,logged_date date not null,weight_kg numeric(7,2) not null check(weight_kg between 25 and 500),notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,logged_date));
create trigger weight_logs_updated before update on public.weight_logs for each row execute function public.set_updated_at();
create table public.recipes(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,name text not null,description text,servings numeric(10,2) not null check(servings>0),preparation_notes text,tags text[] not null default '{}',meal_category text,current_version_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create trigger recipes_updated before update on public.recipes for each row execute function public.set_updated_at();
create table public.recipe_versions(id uuid primary key default gen_random_uuid(),recipe_id uuid not null references public.recipes on delete cascade,version integer not null,total_weight_grams numeric(14,4) not null check(total_weight_grams>0),servings numeric(10,2) not null check(servings>0),created_at timestamptz not null default now(),unique(recipe_id,version));
alter table public.recipes add constraint recipes_current_version_fk foreign key(current_version_id) references public.recipe_versions;
create table public.recipe_ingredients(id uuid primary key default gen_random_uuid(),recipe_version_id uuid not null references public.recipe_versions on delete cascade,food_id uuid not null references public.foods,food_version_id uuid not null references public.food_versions,food_name_snapshot text not null,grams numeric(14,4) not null check(grams>0),sort_order integer not null default 0);
create table public.recipe_ingredient_nutrient_snapshots(id uuid primary key default gen_random_uuid(),recipe_ingredient_id uuid not null references public.recipe_ingredients on delete cascade,nutrient_id uuid not null references public.nutrients,amount numeric(18,6),unit_id uuid not null references public.nutrient_units,value_classification text not null,projection_id uuid references public.nutrient_projections,projection_method text,projection_confidence numeric(5,4),lower_bound numeric(18,6),upper_bound numeric(18,6),food_version_id uuid not null references public.food_versions,captured_at timestamptz not null default now(),unique(recipe_ingredient_id,nutrient_id));
create table public.recipe_nutrient_snapshots(id uuid primary key default gen_random_uuid(),recipe_version_id uuid not null references public.recipe_versions on delete cascade,nutrient_id uuid not null references public.nutrients,unit_id uuid not null references public.nutrient_units,confirmed_amount numeric(18,6) not null default 0,calculated_amount numeric(18,6) not null default 0,projected_amount numeric(18,6) not null default 0,total_excluding_projections numeric(18,6) not null default 0,total_including_projections numeric(18,6) not null default 0,lower_bound numeric(18,6),upper_bound numeric(18,6),projected_percentage numeric(8,4) not null default 0,unique(recipe_version_id,nutrient_id));
create table public.saved_meals(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,name text not null,description text,default_meal_type text references public.meal_types(key),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create trigger saved_meals_updated before update on public.saved_meals for each row execute function public.set_updated_at();
create table public.saved_meal_items(id uuid primary key default gen_random_uuid(),saved_meal_id uuid not null references public.saved_meals on delete cascade,food_id uuid not null references public.foods,food_version_id uuid not null references public.food_versions,food_name_snapshot text not null,brand_snapshot text,grams numeric(14,4) not null check(grams>0),notes text,sort_order integer not null default 0);

create or replace function public.snapshot_recipe_ingredient(p_ingredient_id uuid) returns void language plpgsql security definer set search_path='' as $$
declare ingredient public.recipe_ingredients%rowtype;
begin select ri.* into ingredient from public.recipe_ingredients ri join public.recipe_versions rv on rv.id=ri.recipe_version_id join public.recipes r on r.id=rv.recipe_id where ri.id=p_ingredient_id and r.user_id=auth.uid();if ingredient.id is null then raise exception 'Ingredient not found';end if;
 insert into public.recipe_ingredient_nutrient_snapshots(recipe_ingredient_id,nutrient_id,amount,unit_id,value_classification,food_version_id)
 select ingredient.id,nutrient_id,case when amount_per_100g is null then null else round(amount_per_100g*ingredient.grams/100,6) end,unit_id,case when classification in('not_reported','not_applicable','confirmed_zero','user_entered') then classification else 'calculated' end,ingredient.food_version_id from public.food_version_nutrients where food_version_id=ingredient.food_version_id;
 insert into public.recipe_ingredient_nutrient_snapshots(recipe_ingredient_id,nutrient_id,amount,unit_id,value_classification,projection_id,projection_method,projection_confidence,lower_bound,upper_bound,food_version_id)
 select ingredient.id,p.nutrient_id,round(p.value*ingredient.grams/100,6),p.unit_id,'projected',p.id,pm.key,p.confidence_score,round(coalesce(p.lower_bound,p.value)*ingredient.grams/100,6),round(coalesce(p.upper_bound,p.value)*ingredient.grams/100,6),ingredient.food_version_id from public.nutrient_projections p join public.projection_methods pm on pm.id=p.projection_method_id join public.projection_method_versions pmv on pmv.id=p.projection_method_version_id cross join public.projection_settings settings where p.food_version_id=ingredient.food_version_id and p.status='approved' and p.confidence_score>=greatest(settings.minimum_included_threshold,pmv.minimum_confidence) and(p.confidence_category<>'experimental' or settings.experimental_enabled) and not exists(select 1 from public.food_version_nutrients exact where exact.food_version_id=ingredient.food_version_id and exact.nutrient_id=p.nutrient_id and exact.classification not in('not_reported','not_applicable')) on conflict(recipe_ingredient_id,nutrient_id) do nothing;
end $$;
revoke all on function public.snapshot_recipe_ingredient(uuid) from public,anon;grant execute on function public.snapshot_recipe_ingredient(uuid) to authenticated;

create or replace function public.recalculate_recipe(p_recipe_version_id uuid) returns void language plpgsql security definer set search_path='' as $$
begin if not exists(select 1 from public.recipe_versions rv join public.recipes r on r.id=rv.recipe_id where rv.id=p_recipe_version_id and r.user_id=auth.uid()) then raise exception 'Recipe not found';end if;
 delete from public.recipe_nutrient_snapshots where recipe_version_id=p_recipe_version_id;
 insert into public.recipe_nutrient_snapshots(recipe_version_id,nutrient_id,unit_id,confirmed_amount,calculated_amount,projected_amount,total_excluding_projections,total_including_projections,lower_bound,upper_bound,projected_percentage)
 select p_recipe_version_id,s.nutrient_id,s.unit_id,coalesce(sum(s.amount) filter(where s.value_classification in('measured','provider_reported','confirmed_zero')),0),coalesce(sum(s.amount) filter(where s.value_classification='calculated'),0),coalesce(sum(s.amount) filter(where s.value_classification='projected'),0),coalesce(sum(s.amount) filter(where s.value_classification<>'projected'),0),coalesce(sum(s.amount),0),sum(coalesce(s.lower_bound,s.amount)),sum(coalesce(s.upper_bound,s.amount)),case when coalesce(sum(s.amount),0)>0 then round(coalesce(sum(s.amount) filter(where s.value_classification='projected'),0)/sum(s.amount)*100,4) else 0 end from public.recipe_ingredients i join public.recipe_ingredient_nutrient_snapshots s on s.recipe_ingredient_id=i.id where i.recipe_version_id=p_recipe_version_id and s.amount is not null group by s.nutrient_id,s.unit_id;
end $$;
revoke all on function public.recalculate_recipe(uuid) from public,anon;grant execute on function public.recalculate_recipe(uuid) to authenticated;

create or replace function public.create_recipe(p_name text,p_description text,p_servings numeric,p_ingredients jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare recipe_id uuid;version_id uuid;item jsonb;food public.foods%rowtype;ingredient_id uuid;grams numeric;total_grams numeric:=0;begin if length(trim(p_name))<2 or p_servings<=0 or jsonb_array_length(p_ingredients)<1 then raise exception 'Invalid recipe';end if;insert into public.recipes(user_id,name,description,servings) values(auth.uid(),trim(p_name),nullif(trim(p_description),''),p_servings) returning id into recipe_id;insert into public.recipe_versions(recipe_id,version,total_weight_grams,servings) values(recipe_id,1,1,p_servings) returning id into version_id;for item in select * from jsonb_array_elements(p_ingredients) loop grams:=(item->>'grams')::numeric;select * into food from public.foods where id=(item->>'food_id')::uuid and deleted_at is null and(is_public or owner_id=auth.uid());if food.id is null or grams<=0 then raise exception 'Invalid recipe ingredient';end if;insert into public.recipe_ingredients(recipe_version_id,food_id,food_version_id,food_name_snapshot,grams,sort_order) values(version_id,food.id,food.current_version_id,food.name,grams,total_grams::integer) returning id into ingredient_id;perform public.snapshot_recipe_ingredient(ingredient_id);total_grams:=total_grams+grams;end loop;update public.recipe_versions set total_weight_grams=total_grams where id=version_id;update public.recipes set current_version_id=version_id where id=recipe_id;perform public.recalculate_recipe(version_id);return recipe_id;end$$;
revoke all on function public.create_recipe(text,text,numeric,jsonb) from public,anon;grant execute on function public.create_recipe(text,text,numeric,jsonb) to authenticated;

create or replace function public.save_diary_meal(p_meal_id uuid,p_name text) returns uuid language plpgsql security definer set search_path='' as $$declare saved_id uuid;begin if length(trim(p_name))<2 then raise exception 'Name required';end if;if not exists(select 1 from public.meals m join public.diary_days d on d.id=m.diary_day_id where m.id=p_meal_id and d.user_id=auth.uid()) then raise exception 'Meal not found';end if;insert into public.saved_meals(user_id,name,default_meal_type) select auth.uid(),trim(p_name),mt.key from public.meals m join public.meal_types mt on mt.id=m.meal_type_id where m.id=p_meal_id returning id into saved_id;insert into public.saved_meal_items(saved_meal_id,food_id,food_version_id,food_name_snapshot,brand_snapshot,grams,notes,sort_order) select saved_id,food_id,food_version_id,food_name_snapshot,brand_snapshot,gram_weight,notes,sort_order from public.meal_entries where meal_id=p_meal_id;return saved_id;end$$;
revoke all on function public.save_diary_meal(uuid,text) from public,anon;grant execute on function public.save_diary_meal(uuid,text) to authenticated;
create or replace function public.log_saved_meal(p_saved_meal_id uuid,p_date date,p_meal_type text) returns integer language plpgsql security definer set search_path='' as $$declare item record;v_day uuid;v_meal uuid;v_type uuid;v_entry uuid;added integer:=0;begin if not exists(select 1 from public.saved_meals where id=p_saved_meal_id and user_id=auth.uid() and deleted_at is null) then raise exception 'Saved meal not found';end if;select id into v_type from public.meal_types where key=p_meal_type;insert into public.diary_days(user_id,diary_date) values(auth.uid(),p_date) on conflict(user_id,diary_date) do update set diary_date=excluded.diary_date returning id into v_day;insert into public.meals(diary_day_id,meal_type_id,sort_order) values(v_day,v_type,(select sort_order from public.meal_types where id=v_type)) on conflict(diary_day_id,meal_type_id) do update set meal_type_id=excluded.meal_type_id returning id into v_meal;for item in select * from public.saved_meal_items where saved_meal_id=p_saved_meal_id order by sort_order loop insert into public.meal_entries(meal_id,food_id,food_version_id,food_name_snapshot,brand_snapshot,quantity,unit,gram_weight,logged_at,notes,sort_order) values(v_meal,item.food_id,item.food_version_id,item.food_name_snapshot,item.brand_snapshot,item.grams,'g',item.grams,p_date::timestamp at time zone 'UTC',item.notes,item.sort_order) returning id into v_entry;perform public.capture_entry_nutrients(v_entry,item.food_version_id,item.grams,'logged from saved meal using preserved food version');added:=added+1;end loop;return added;end$$;
revoke all on function public.log_saved_meal(uuid,date,text) from public,anon;grant execute on function public.log_saved_meal(uuid,date,text) to authenticated;

alter table public.favorite_foods enable row level security;alter table public.weight_logs enable row level security;alter table public.recipes enable row level security;alter table public.recipe_versions enable row level security;alter table public.recipe_ingredients enable row level security;alter table public.recipe_ingredient_nutrient_snapshots enable row level security;alter table public.recipe_nutrient_snapshots enable row level security;alter table public.saved_meals enable row level security;alter table public.saved_meal_items enable row level security;
create policy favorites_own on public.favorite_foods for all using(user_id=auth.uid()) with check(user_id=auth.uid());create policy weights_own on public.weight_logs for all using(user_id=auth.uid()) with check(user_id=auth.uid());create policy recipes_own on public.recipes for all using(user_id=auth.uid()) with check(user_id=auth.uid());create policy recipe_versions_own on public.recipe_versions for all using(exists(select 1 from public.recipes r where r.id=recipe_id and r.user_id=auth.uid())) with check(exists(select 1 from public.recipes r where r.id=recipe_id and r.user_id=auth.uid()));create policy recipe_ingredients_own on public.recipe_ingredients for all using(exists(select 1 from public.recipe_versions rv join public.recipes r on r.id=rv.recipe_id where rv.id=recipe_version_id and r.user_id=auth.uid())) with check(exists(select 1 from public.recipe_versions rv join public.recipes r on r.id=rv.recipe_id where rv.id=recipe_version_id and r.user_id=auth.uid()));create policy recipe_ingredient_snapshots_read on public.recipe_ingredient_nutrient_snapshots for select using(exists(select 1 from public.recipe_ingredients i join public.recipe_versions rv on rv.id=i.recipe_version_id join public.recipes r on r.id=rv.recipe_id where i.id=recipe_ingredient_id and r.user_id=auth.uid()));create policy recipe_totals_read on public.recipe_nutrient_snapshots for select using(exists(select 1 from public.recipe_versions rv join public.recipes r on r.id=rv.recipe_id where rv.id=recipe_version_id and r.user_id=auth.uid()));create policy saved_meals_own on public.saved_meals for all using(user_id=auth.uid()) with check(user_id=auth.uid());create policy saved_meal_items_own on public.saved_meal_items for all using(exists(select 1 from public.saved_meals sm where sm.id=saved_meal_id and sm.user_id=auth.uid())) with check(exists(select 1 from public.saved_meals sm where sm.id=saved_meal_id and sm.user_id=auth.uid()));
commit;
