begin;
create table public.rate_limit_buckets(scope text not null,subject_key text not null,window_start timestamptz not null,request_count integer not null default 1,expires_at timestamptz not null,primary key(scope,subject_key,window_start));
create index rate_limit_expiry on public.rate_limit_buckets(expires_at);
create table public.app_settings(key text primary key,value jsonb not null,description text not null,updated_by uuid references auth.users,updated_at timestamptz not null default now());
create table public.operational_events(id bigint generated always as identity primary key,event_type text not null,severity text not null check(severity in('info','warning','error','critical')),correlation_id uuid,context jsonb not null default '{}',occurred_at timestamptz not null default now());
create index operational_events_time on public.operational_events(occurred_at desc);
insert into public.app_settings(key,value,description) values('maintenance_mode','false','Disable user mutations during controlled maintenance'),('data_retention','{"operational_event_days":30,"provider_log_days":30,"stripe_event_days":365}','Operational data-retention configuration');
create or replace function public.consume_rate_limit(p_scope text,p_subject text,p_limit integer,p_window_seconds integer) returns table(allowed boolean,remaining integer,retry_after integer) language plpgsql security definer set search_path='' as $$declare bucket_start timestamptz;current_count integer;begin if p_limit<1 or p_window_seconds<1 or length(p_scope)>100 or length(p_subject)>200 then raise exception 'Invalid rate limit';end if;bucket_start:=to_timestamp(floor(extract(epoch from now())/p_window_seconds)*p_window_seconds);insert into public.rate_limit_buckets(scope,subject_key,window_start,request_count,expires_at) values(p_scope,p_subject,bucket_start,1,bucket_start+make_interval(secs=>p_window_seconds)) on conflict(scope,subject_key,window_start) do update set request_count=public.rate_limit_buckets.request_count+1 returning request_count into current_count;return query select current_count<=p_limit,greatest(p_limit-current_count,0),case when current_count>p_limit then greatest(ceil(extract(epoch from(bucket_start+make_interval(secs=>p_window_seconds)-now())))::integer,1) else 0 end;end$$;
revoke all on function public.consume_rate_limit(text,text,integer,integer) from public,anon;grant execute on function public.consume_rate_limit(text,text,integer,integer) to authenticated;
create or replace function public.purge_expired_operational_data() returns table(table_name text,deleted_count bigint) language plpgsql security definer set search_path='' as $$declare count_value bigint;begin if not public.has_permission('system_health.read') then raise exception 'Permission denied';end if;delete from public.rate_limit_buckets where expires_at<now();get diagnostics count_value=row_count;return query select 'rate_limit_buckets'::text,count_value;delete from public.operational_events where occurred_at<now()-interval '30 days';get diagnostics count_value=row_count;return query select 'operational_events'::text,count_value;delete from public.provider_api_logs where created_at<now()-interval '30 days';get diagnostics count_value=row_count;return query select 'provider_api_logs'::text,count_value;end$$;
revoke all on function public.purge_expired_operational_data() from public,anon;grant execute on function public.purge_expired_operational_data() to authenticated;
alter table public.rate_limit_buckets enable row level security;alter table public.app_settings enable row level security;alter table public.operational_events enable row level security;
create policy app_settings_admin_read on public.app_settings for select using(public.has_permission('system_health.read'));create policy app_settings_manage on public.app_settings for all using(public.has_permission('feature_flags.manage')) with check(public.has_permission('feature_flags.manage'));create policy operational_events_read on public.operational_events for select using(public.has_permission('system_health.read'));
-- Rate-limit buckets and operational-event writes are server-function/service-role only.
commit;
