begin;
insert into public.nutrient_categories(key,name,sort_order) values('sugars','Sugars',5),('amino_acids','Amino acids',6),('trace_elements','Trace elements',7),('bioactive_compounds','Other food components',8),('polyphenols','Polyphenols and flavonoids',9) on conflict(key) do update set name=excluded.name,sort_order=excluded.sort_order;
with definitions(key,name,category,unit)as(values
('total_sugars','Total sugars','sugars','g'),('added_sugars','Added sugars','sugars','g'),('glucose','Glucose','sugars','g'),('fructose','Fructose','sugars','g'),('sucrose','Sucrose','sugars','g'),('lactose','Lactose','sugars','g'),
('saturated_fat','Saturated fat','fatty_acids','g'),('monounsaturated_fat','Monounsaturated fat','fatty_acids','g'),('polyunsaturated_fat','Polyunsaturated fat','fatty_acids','g'),('trans_fat','Trans fat','fatty_acids','g'),('cholesterol','Cholesterol','fatty_acids','mg'),('omega_6','Omega-6 fatty acids','fatty_acids','mg'),('ala','Alpha-linolenic acid (ALA)','fatty_acids','mg'),('epa','Eicosapentaenoic acid (EPA)','fatty_acids','mg'),('dha','Docosahexaenoic acid (DHA)','fatty_acids','mg'),
('leucine','Leucine','amino_acids','g'),('lysine','Lysine','amino_acids','g'),('methionine','Methionine','amino_acids','g'),('tryptophan','Tryptophan','amino_acids','g'),('threonine','Threonine','amino_acids','g'),('isoleucine','Isoleucine','amino_acids','g'),('phenylalanine','Phenylalanine','amino_acids','g'),('tyrosine','Tyrosine','amino_acids','g'),('valine','Valine','amino_acids','g'),
('iodine','Iodine','trace_elements','mcg'),('chromium','Chromium','trace_elements','mcg'),('molybdenum','Molybdenum','trace_elements','mcg'),('fluoride','Fluoride','trace_elements','mg'),('chloride','Chloride','trace_elements','mg'),('boron','Boron','trace_elements','mg'),
('beta_carotene','Beta-carotene','bioactive_compounds','mcg'),('alpha_carotene','Alpha-carotene','bioactive_compounds','mcg'),('lycopene','Lycopene','bioactive_compounds','mcg'),('lutein_zeaxanthin','Lutein and zeaxanthin','bioactive_compounds','mcg'),('phytosterols','Phytosterols','bioactive_compounds','mg'),('caffeine','Caffeine','bioactive_compounds','mg'),('alcohol','Alcohol','bioactive_compounds','g'),('water','Water','bioactive_compounds','g'),
('total_polyphenols','Total polyphenols','polyphenols','mg'),('flavonols','Flavonols','polyphenols','mg'),('flavan_3_ols','Flavan-3-ols','polyphenols','mg'),('flavanones','Flavanones','polyphenols','mg'),('anthocyanidins','Anthocyanidins','polyphenols','mg'),('isoflavones','Isoflavones','polyphenols','mg'),('proanthocyanidins','Proanthocyanidins','polyphenols','mg'),('flavones','Flavones','polyphenols','mg'))
insert into public.nutrients(key,name,category_id,default_unit_id,is_core)select d.key,d.name,c.id,u.id,true from definitions d join public.nutrient_categories c on c.key=d.category join public.nutrient_units u on u.symbol=d.unit on conflict(key)do update set name=excluded.name,category_id=excluded.category_id,default_unit_id=excluded.default_unit_id,is_core=true;

insert into public.user_nutrient_targets(user_id,nutrient_id,target_amount,minimum_amount,maximum_amount,unit_id,target_type,methodology_id,calculation_version)
select p.user_id,n.id,null,null,null,n.default_unit_id,'informational',m.id,'advanced-v1' from public.nutrition_profiles p cross join public.nutrients n join public.target_methodologies m on m.key='us_daily_value' where n.category_id in(select id from public.nutrient_categories where key in('sugars','amino_acids','trace_elements','bioactive_compounds','polyphenols')) or n.key in('saturated_fat','monounsaturated_fat','polyunsaturated_fat','trans_fat','cholesterol','omega_6','ala','epa','dha') on conflict(user_id,nutrient_id)do nothing;

create or replace function public.ensure_advanced_informational_targets()returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.user_nutrient_targets(user_id,nutrient_id,target_amount,minimum_amount,maximum_amount,unit_id,target_type,methodology_id,calculation_version)select new.user_id,n.id,null,null,null,n.default_unit_id,'informational',m.id,'advanced-v1' from public.nutrients n join public.target_methodologies m on m.key='us_daily_value' where n.category_id in(select id from public.nutrient_categories where key in('sugars','amino_acids','trace_elements','bioactive_compounds','polyphenols')) or n.key in('saturated_fat','monounsaturated_fat','polyunsaturated_fat','trans_fat','cholesterol','omega_6','ala','epa','dha') on conflict(user_id,nutrient_id)do nothing;return new;end$$;
drop trigger if exists nutrition_profile_advanced_targets on public.nutrition_profiles;create trigger nutrition_profile_advanced_targets after insert or update on public.nutrition_profiles for each row execute function public.ensure_advanced_informational_targets();
commit;
