begin;
insert into public.permissions(key,description) values ('projections.manage','Create, review, recalculate, and invalidate nutrient projections') on conflict do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r cross join public.permissions p where r.key='owner' and p.key='projections.manage' on conflict do nothing;
alter table public.profiles add column projection_display_mode text not null default 'eligible' check(projection_display_mode in ('eligible','confirmed_only'));

create table public.projection_settings (id boolean primary key default true check(id),high_threshold numeric(5,4) not null default .85,moderate_threshold numeric(5,4) not null default .65,low_threshold numeric(5,4) not null default .40,minimum_included_threshold numeric(5,4) not null default .65,experimental_enabled boolean not null default false,updated_by uuid references auth.users,updated_at timestamptz not null default now(),check(high_threshold>moderate_threshold and moderate_threshold>low_threshold and low_threshold>=0 and high_threshold<=1));
insert into public.projection_settings(id) values(true);
create table public.projection_methods (id uuid primary key default gen_random_uuid(),key text not null unique,name text not null,description text not null,is_active boolean not null default true,created_at timestamptz not null default now());
create table public.projection_method_versions (id uuid primary key default gen_random_uuid(),method_id uuid not null references public.projection_methods,version text not null,algorithm_summary text not null,minimum_confidence numeric(5,4) not null default .40,created_at timestamptz not null default now(),unique(method_id,version));
create table public.nutrient_projections (id uuid primary key default gen_random_uuid(),food_id uuid not null references public.foods,food_version_id uuid not null references public.food_versions,nutrient_id uuid not null references public.nutrients,value numeric(18,6) not null check(value>=0),unit_id uuid not null references public.nutrient_units,lower_bound numeric(18,6),upper_bound numeric(18,6),confidence_score numeric(5,4) not null check(confidence_score between 0 and 1),confidence_category text not null check(confidence_category in ('high','moderate','low','experimental')),projection_method_id uuid not null references public.projection_methods,projection_method_version_id uuid not null references public.projection_method_versions,status text not null default 'pending' check(status in ('pending','approved','rejected','invalidated','superseded')),explanation text not null,reference_count integer not null default 0,similarity_score numeric(5,4),created_by uuid references auth.users,reviewed_by uuid references auth.users,reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),invalidated_at timestamptz,invalidation_reason text,check(lower_bound is null or lower_bound<=value),check(upper_bound is null or upper_bound>=value));
create unique index one_active_projection on public.nutrient_projections(food_version_id,nutrient_id) where status in ('pending','approved');
create trigger nutrient_projections_updated before update on public.nutrient_projections for each row execute function public.set_updated_at();
create table public.nutrient_projection_references (id uuid primary key default gen_random_uuid(),projection_id uuid not null references public.nutrient_projections on delete cascade,reference_food_id uuid references public.foods,reference_food_version_id uuid references public.food_versions,reference_nutrient_id uuid references public.nutrients,reference_value numeric(18,6),reference_unit text,reference_weight numeric(18,6),similarity_score numeric(5,4),source_priority integer,citation text,notes text);
create table public.projection_reviews (id uuid primary key default gen_random_uuid(),projection_id uuid not null references public.nutrient_projections,reviewer_id uuid not null references auth.users,decision text not null check(decision in ('approved','rejected','recalculate','invalidated')),reason text not null check(length(trim(reason))>=10),created_at timestamptz not null default now());
create table public.projection_recalculations (id uuid primary key default gen_random_uuid(),projection_id uuid not null references public.nutrient_projections,requested_by uuid references auth.users,reason text not null,algorithm_version text not null,status text not null default 'queued' check(status in ('queued','running','completed','failed')),created_at timestamptz not null default now(),completed_at timestamptz,error text);
alter table public.meal_entry_nutrient_snapshots add column projection_id uuid references public.nutrient_projections,add column projection_method text,add column projection_confidence numeric(5,4),add column projection_lower_bound numeric(18,6),add column projection_upper_bound numeric(18,6);

create or replace function public.projection_category(score numeric) returns text language sql immutable set search_path='' as $$select case when score>=.85 then 'high' when score>=.65 then 'moderate' when score>=.40 then 'low' else 'experimental' end$$;
create or replace function public.enforce_projection_confidence() returns trigger language plpgsql set search_path='' as $$begin new.confidence_category=public.projection_category(new.confidence_score);return new;end$$;
create trigger projection_confidence_before_write before insert or update of confidence_score on public.nutrient_projections for each row execute function public.enforce_projection_confidence();
create or replace function public.review_projection(p_projection_id uuid,p_decision text,p_reason text) returns void language plpgsql security definer set search_path='' as $$
declare next_status text;
begin
 if not public.has_permission('projections.manage') then raise exception 'Permission denied';end if;
 if length(trim(p_reason))<10 then raise exception 'A meaningful reason is required';end if;
 next_status:=case p_decision when 'approved' then 'approved' when 'rejected' then 'rejected' when 'invalidated' then 'invalidated' else null end;
 if next_status is null then raise exception 'Invalid decision';end if;
 update public.nutrient_projections set status=next_status,reviewed_by=auth.uid(),reviewed_at=now(),invalidated_at=case when next_status='invalidated' then now() else invalidated_at end,invalidation_reason=case when next_status='invalidated' then trim(p_reason) else invalidation_reason end where id=p_projection_id and status in ('pending','approved');
 if not found then raise exception 'Projection is not reviewable';end if;
 insert into public.projection_reviews(projection_id,reviewer_id,decision,reason) values(p_projection_id,auth.uid(),p_decision,trim(p_reason));
 insert into public.audit_logs(actor_id,action,target_type,target_id,reason) values(auth.uid(),'projection.'||p_decision,'nutrient_projection',p_projection_id::text,trim(p_reason));
end $$;
revoke all on function public.review_projection(uuid,text,text) from public,anon;grant execute on function public.review_projection(uuid,text,text) to authenticated;
create or replace function public.request_projection_recalculation(p_projection_id uuid,p_reason text) returns uuid language plpgsql security definer set search_path='' as $$
declare request_id uuid;version text;
begin
 if not public.has_permission('projections.manage') then raise exception 'Permission denied';end if;if length(trim(p_reason))<10 then raise exception 'A meaningful reason is required';end if;
 select pmv.version into version from public.nutrient_projections p join public.projection_method_versions pmv on pmv.id=p.projection_method_version_id where p.id=p_projection_id;if version is null then raise exception 'Projection not found';end if;
 insert into public.projection_recalculations(projection_id,requested_by,reason,algorithm_version) values(p_projection_id,auth.uid(),trim(p_reason),version) returning id into request_id;
 insert into public.projection_reviews(projection_id,reviewer_id,decision,reason) values(p_projection_id,auth.uid(),'recalculate',trim(p_reason));insert into public.audit_logs(actor_id,action,target_type,target_id,reason) values(auth.uid(),'projection.recalculate','nutrient_projection',p_projection_id::text,trim(p_reason));return request_id;
end $$;
revoke all on function public.request_projection_recalculation(uuid,text) from public,anon;grant execute on function public.request_projection_recalculation(uuid,text) to authenticated;

alter table public.projection_settings enable row level security;alter table public.projection_methods enable row level security;alter table public.projection_method_versions enable row level security;alter table public.nutrient_projections enable row level security;alter table public.nutrient_projection_references enable row level security;alter table public.projection_reviews enable row level security;alter table public.projection_recalculations enable row level security;
create policy projection_settings_read on public.projection_settings for select to authenticated using(true);create policy projection_settings_manage on public.projection_settings for update using(public.has_permission('projections.manage')) with check(public.has_permission('projections.manage'));
create policy projection_methods_read on public.projection_methods for select to authenticated using(true);create policy projection_method_versions_read on public.projection_method_versions for select to authenticated using(true);
create policy projections_read on public.nutrient_projections for select to authenticated using(exists(select 1 from public.foods f where f.id=food_id and(f.is_public or f.owner_id=auth.uid())));create policy projections_manage on public.nutrient_projections for all using(public.has_permission('projections.manage')) with check(public.has_permission('projections.manage'));
create policy projection_references_read on public.nutrient_projection_references for select to authenticated using(exists(select 1 from public.nutrient_projections p join public.foods f on f.id=p.food_id where p.id=projection_id and(f.is_public or f.owner_id=auth.uid())));create policy projection_references_manage on public.nutrient_projection_references for all using(public.has_permission('projections.manage')) with check(public.has_permission('projections.manage'));
create policy projection_reviews_manage on public.projection_reviews for all using(public.has_permission('projections.manage')) with check(public.has_permission('projections.manage'));create policy projection_recalculations_manage on public.projection_recalculations for all using(public.has_permission('projections.manage')) with check(public.has_permission('projections.manage'));

create or replace function public.capture_entry_nutrients(p_entry_id uuid,p_food_version_id uuid,p_grams numeric,p_basis text) returns void language plpgsql security definer set search_path='' as $$
begin
 insert into public.meal_entry_nutrient_snapshots(meal_entry_id,nutrient_id,amount,unit_id,value_classification,source_classification,source_amount_per_100g,calculation_basis,food_version_id)
 select p_entry_id,nutrient_id,case when amount_per_100g is null then null else round(amount_per_100g*p_grams/100,6) end,unit_id,case when classification in ('not_reported','not_applicable','confirmed_zero','user_entered','projected') then classification else 'calculated' end,classification,amount_per_100g,p_basis,p_food_version_id from public.food_version_nutrients where food_version_id=p_food_version_id;
 insert into public.meal_entry_nutrient_snapshots(meal_entry_id,nutrient_id,amount,unit_id,value_classification,source_classification,source_amount_per_100g,calculation_basis,food_version_id,projection_id,projection_method,projection_confidence,projection_lower_bound,projection_upper_bound)
 select p_entry_id,p.nutrient_id,round(p.value*p_grams/100,6),p.unit_id,'projected','projected',p.value,p_basis,p_food_version_id,p.id,pm.key,p.confidence_score,case when p.lower_bound is null then null else round(p.lower_bound*p_grams/100,6) end,case when p.upper_bound is null then null else round(p.upper_bound*p_grams/100,6) end
 from public.nutrient_projections p join public.projection_methods pm on pm.id=p.projection_method_id join public.projection_method_versions pmv on pmv.id=p.projection_method_version_id cross join public.projection_settings settings
 where p.food_version_id=p_food_version_id and p.status='approved' and p.confidence_score>=greatest(settings.minimum_included_threshold,pmv.minimum_confidence) and (p.confidence_category<>'experimental' or settings.experimental_enabled)
 and not exists(select 1 from public.food_version_nutrients exact where exact.food_version_id=p_food_version_id and exact.nutrient_id=p.nutrient_id and exact.classification not in('not_reported','not_applicable'))
 on conflict(meal_entry_id,nutrient_id) do nothing;
end $$;
revoke all on function public.capture_entry_nutrients(uuid,uuid,numeric,text) from public,anon,authenticated;

create or replace function public.log_food_entry(p_food_id uuid,p_grams numeric,p_meal_type text,p_date date,p_time time default '12:00',p_notes text default null) returns uuid language plpgsql security definer set search_path='' as $$
declare v_day uuid;v_meal uuid;v_entry uuid;v_food public.foods%rowtype;v_meal_type uuid;
begin
 if auth.uid() is null then raise exception 'Authentication required';end if;if p_grams<=0 or p_grams>10000 then raise exception 'Invalid serving amount';end if;
 select * into v_food from public.foods where id=p_food_id and deleted_at is null and(is_public or owner_id=auth.uid());if v_food.id is null then raise exception 'Food not found';end if;
 select id into v_meal_type from public.meal_types where key=p_meal_type;if v_meal_type is null then raise exception 'Meal type not found';end if;
 insert into public.diary_days(user_id,diary_date) values(auth.uid(),p_date) on conflict(user_id,diary_date) do update set diary_date=excluded.diary_date returning id into v_day;
 insert into public.meals(diary_day_id,meal_type_id,sort_order) values(v_day,v_meal_type,(select sort_order from public.meal_types where id=v_meal_type)) on conflict(diary_day_id,meal_type_id) do update set meal_type_id=excluded.meal_type_id returning id into v_meal;
 insert into public.meal_entries(meal_id,food_id,food_version_id,food_name_snapshot,brand_snapshot,quantity,unit,gram_weight,logged_at,notes) values(v_meal,v_food.id,v_food.current_version_id,v_food.name,v_food.brand,p_grams,'g',p_grams,(p_date+p_time) at time zone 'UTC',nullif(trim(p_notes),'')) returning id into v_entry;
 perform public.capture_entry_nutrients(v_entry,v_food.current_version_id,p_grams,'scaled from per-100g value using logged gram weight');return v_entry;
end $$;
revoke all on function public.log_food_entry(uuid,numeric,text,date,time,text) from public,anon;grant execute on function public.log_food_entry(uuid,numeric,text,date,time,text) to authenticated;

create or replace function public.update_food_entry(p_entry_id uuid,p_grams numeric,p_meal_type text,p_notes text default null) returns void language plpgsql security definer set search_path='' as $$
declare v_entry public.meal_entries%rowtype;v_day uuid;v_meal uuid;v_meal_type uuid;
begin
 if p_grams<=0 or p_grams>10000 then raise exception 'Invalid serving amount';end if;select e.* into v_entry from public.meal_entries e join public.meals m on m.id=e.meal_id join public.diary_days d on d.id=m.diary_day_id where e.id=p_entry_id and d.user_id=auth.uid() for update;if v_entry.id is null then raise exception 'Entry not found';end if;
 select m.diary_day_id into v_day from public.meals m where m.id=v_entry.meal_id;select id into v_meal_type from public.meal_types where key=p_meal_type;if v_meal_type is null then raise exception 'Meal type not found';end if;
 insert into public.meals(diary_day_id,meal_type_id,sort_order) values(v_day,v_meal_type,(select sort_order from public.meal_types where id=v_meal_type)) on conflict(diary_day_id,meal_type_id) do update set meal_type_id=excluded.meal_type_id returning id into v_meal;
 update public.meal_entries set meal_id=v_meal,quantity=p_grams,unit='g',gram_weight=p_grams,notes=nullif(trim(p_notes),'') where id=p_entry_id;delete from public.meal_entry_nutrient_snapshots where meal_entry_id=p_entry_id;perform public.capture_entry_nutrients(p_entry_id,v_entry.food_version_id,p_grams,'entry edited; rescaled from originally logged food version');
end $$;

create or replace function public.duplicate_food_entry(p_entry_id uuid) returns uuid language plpgsql security definer set search_path='' as $$
declare source public.meal_entries%rowtype;new_id uuid;
begin select e.* into source from public.meal_entries e join public.meals m on m.id=e.meal_id join public.diary_days d on d.id=m.diary_day_id where e.id=p_entry_id and d.user_id=auth.uid();if source.id is null then raise exception 'Entry not found';end if;
 insert into public.meal_entries(meal_id,food_id,food_version_id,serving_id,food_name_snapshot,brand_snapshot,quantity,unit,gram_weight,logged_at,notes,sort_order) values(source.meal_id,source.food_id,source.food_version_id,source.serving_id,source.food_name_snapshot,source.brand_snapshot,source.quantity,source.unit,source.gram_weight,source.logged_at,source.notes,source.sort_order+1) returning id into new_id;
 insert into public.meal_entry_nutrient_snapshots(meal_entry_id,nutrient_id,amount,unit_id,value_classification,source_classification,source_amount_per_100g,calculation_basis,food_version_id,captured_at,projection_id,projection_method,projection_confidence,projection_lower_bound,projection_upper_bound) select new_id,nutrient_id,amount,unit_id,value_classification,source_classification,source_amount_per_100g,'duplicated from diary snapshot',food_version_id,now(),projection_id,projection_method,projection_confidence,projection_lower_bound,projection_upper_bound from public.meal_entry_nutrient_snapshots where meal_entry_id=p_entry_id;return new_id;
end $$;

insert into public.projection_methods(id,key,name,description) values ('90000000-0000-0000-0000-000000000001','generic_food_reference','Generic food reference projection','Projects a missing nutrient from a tightly matched generic food'),('90000000-0000-0000-0000-000000000002','same_product_family','Same product family projection','Uses closely related formulations from the same product family'),('90000000-0000-0000-0000-000000000003','ingredient_weighted','Ingredient-weighted projection','Uses documented ingredient quantities and uncertainty');
insert into public.projection_method_versions(id,method_id,version,algorithm_summary,minimum_confidence) values ('91000000-0000-0000-0000-000000000001','90000000-0000-0000-0000-000000000001','1.0','Copy matched per-100g nutrient value with similarity and variance penalties',.65),('91000000-0000-0000-0000-000000000002','90000000-0000-0000-0000-000000000002','1.0','Median of closely related same-brand formulations',.65),('91000000-0000-0000-0000-000000000003','90000000-0000-0000-0000-000000000003','1.0','Weighted ingredient nutrient sum with uncertainty bounds',.65);
commit;
